<a href="https://colab.research.google.com/github/Felipeosouz/Formacao-Cientista-de-Dados/blob/main/Machine%20Learning/Neural%20Networks%20e%20Deep%20Learning/RedeNeural.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn import datasets
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils

base = datasets.load_iris()
previsores = base.data
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
# Transformação da classe para o formato "dummy", pois temos uma rede neural com 3 neurônios na camada de saída
classe_dummy = np_utils.to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [15]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores,
                                                                  classe_dummy,
                                                                  test_size = 0.3,
                                                                  random_state = 0)

In [16]:
# Criação da estrutura da rede neural com a classe Sequential ( sequência de camadas )
modelo = Sequential()

# Primeira camada oculta, 5 neurônios, 4 neurônios de entrada
modelo.add(Dense(units = 5, input_dim = 4))

# Segunda camada oculta
modelo.add(Dense(units = 4))

# Terceira camada oculta
# Função softmax porque temos um problema de classificação com mais de duas classes
# É gerada uma probabilidade em cada neurônio
modelo.add(Dense(units = 3, activation = "softmax"))

#Visualização da estrutura da rede neural
modelo.summary

<bound method Model.summary of <keras.engine.sequential.Sequential object at 0x7fe3004d2700>>

In [17]:
# Configuração dos parâmetros da rede neural ( adam = algoritmo para atualizar os pesos e loss = cálculo do erro )
modelo.compile(optimizer = "adam", loss = "categorical_crossentropy",
               metrics = ["accuracy"])

#Treinamento, dividindo a base de treinamento em uma porção para validação ( validation_data )
modelo.fit(X_treinamento, y_treinamento, epochs = 1000,
           validation_data = (X_teste, y_teste))

Epoch 1/1000
4/4 [==============================] - 1s 73ms/step - loss: 3.2525 - accuracy: 0.3238 - val_loss: 3.4583 - val_accuracy: 0.3556
Epoch 2/1000
4/4 [==============================] - 0s 13ms/step - loss: 3.0212 - accuracy: 0.3238 - val_loss: 3.2064 - val_accuracy: 0.3556
Epoch 3/1000
4/4 [==============================] - 0s 19ms/step - loss: 2.7915 - accuracy: 0.3238 - val_loss: 2.9636 - val_accuracy: 0.3556
Epoch 4/1000
4/4 [==============================] - 0s 19ms/step - loss: 2.5747 - accuracy: 0.3238 - val_loss: 2.7307 - val_accuracy: 0.3556
Epoch 5/1000
4/4 [==============================] - 0s 19ms/step - loss: 2.3737 - accuracy: 0.3238 - val_loss: 2.5068 - val_accuracy: 0.3556
Epoch 6/1000
4/4 [==============================] - 0s 18ms/step - loss: 2.1799 - accuracy: 0.3238 - val_loss: 2.2955 - val_accuracy: 0.3556
Epoch 7/1000
4/4 [==============================] - 0s 15ms/step - loss: 1.9960 - accuracy: 0.3238 - val_loss: 2.0963 - val_accuracy: 0.3556
Epoch 8/1000


In [18]:
# Previsões e mudar a variável para True ou False de acordo com o threshold 0.5
previsoes = modelo.predict(X_teste)
previsoes = (previsoes > 0.5)
previsoes

2/2 [==============================] - 0s 11ms/step


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [19]:
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsao_matrix = [np.argmax(t) for t in previsoes]

confusao = confusion_matrix(y_teste_matrix, y_previsao_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])